version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - gouel-redis:/data

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - gouel-mongo:/data/db

volumes:
  gouel-redis:
  gouel-mongo:
